apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5